### ISSUE TITLE
[BUG] Wheeler consistently crashes to desktop.

### ISSUE THREAD

**Issue by pyriell** [Oghma-Infinium/Apostasy#5]
**Describe the bug**
Any time I press Q to bring up the wheel menu, the game crashes to desktop.

**To Reproduce**
1. Add a weapon to the wheel menu.  I added an iron war axe on the top, and a hunting bow to the right.  These were my starting equipment.
2. Sell the weapon without first removing it from the wheel menu.
3. Press Q.
4. The game will immediately crash, and you can never bring up the wheel menu again.

**Crash Logs**
See attached log file.
[crash-2024-07-24-21-02-18.log](https://github.com/user-attachments/files/16367662/crash-2024-07-24-21-02-18.log)

**Technical (please complete the following information):**
I'll edit this in if it becomes relevant.

**Additional context**
This mod has 115 bug reports when I checked the page, and at least a third of what I saw on the first three pages involved "CTD" or "crash".  It should probably be removed.  Something that looks almost identical to my issue was one of the first bugs opened, and it's still unresolved.  The mod hasn't been updated in about a year.

I realize you have a workaround in the FAQ, but why is this inconvenient mod such a necessity?  I'd understand if it was being actively worked on.

**Comment by aljoxo** [comment]
Please do not open an issue on github when it has already been noted [on the FAQ](https://github.com/Oghma-Infinium/Apostasy/blob/main/Documentation/FAQ.md#wheelerdll-crash). 

Closed.

**Comment by aljoxo** [comment]
This issue has been fixed for several versions.
