### ISSUE TITLE
I followed the steps in the article, and video but I don't have the MO2

### ISSUE THREAD

**Issue by DarthDrunky** [Oghma-Infinium/Apostasy#7]
Hi,

I ran through the install of Apostasy a few times now. I followed the instructions and could not find the ModOrganizer.exe file. I followed the instructions on the video most recently and found that the install folder looks quite different from mine. Please see the screenshots. 
What is should be:
![what it should be](https://github.com/user-attachments/assets/a3ad00bd-aea0-4992-8732-576165ded4c2)

What I have:
![what it is 1](https://github.com/user-attachments/assets/298eceb9-ab88-479e-97f7-fa26a034061b)
![what it is 2](https://github.com/user-attachments/assets/d05493e3-e7b3-48c7-b14b-ea9c77d82b99)

Thank you in advance for assistance you can provide.

Thanks,

**Comment by aljoxo** [comment]
1. Make sure that `D:\Apostasy` was your install directory in the Wabbajack App
2. Make sure Wabbajack says installation was successful.

If you want further install support then you can join the discord (linked in the readme), I am not going to troubleshoot support issues over github, it is not a forum that is efficient for this type of support.
